server:
  port: 9010
spring:
  application:
    name:  wanttosay-friend
  datasource:
    url: jdbc:mysql://localhost:3306/wanttosay_friend?characterEncoding=utf-8
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  jwt:
    config:
      key: coolhy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
      instance:
        prefer-ip-address: true