server:
  port: 9011
spring:
  application:
    name:  wanttosay-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
  wanttosay-gathering: #活动
    path: /gathering/** #配置请求URL的规则
    serviceId: wanttosay-gathering #指定eureka注册中心的服务id
  wanttosay-article: #文章
    path: /article/**
    serviceId: wanttosay-article #指定eureka注册中心的服务id
  wanttosay-qa: #问答
      path: /qa/**
      serviceId: wanttosay-qa #指定eureka注册中心的服务id
  wanttosay-friend: #朋友
      path: /friend/**
      serviceId: wanttosay-friend #指定eureka注册中心的服务id
  wanttosay-base: #基础
    path: /base/**
    serviceId: wanttosay-base #指定eureka注册中心的服务id
  wanttosay-user: #用户
    path: /user/**
    serviceId: wanttosay-user #指定eureka注册中心的服务id
  wanttosay-recruit: #文章
    path: /recruit/**
    serviceId: wanttosay-recruit #指定eureka注册中心的服务id
  wanttosay-spit: #吐槽
    path: /spit/**
    serviceId: wanttosay-spit #指定eureka注册中心的服务id
