server:
  port: 9014
spring:
  application:
    name: tensquare‐spit #指定服务名

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_article
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spitdb
#      spring.data.mongodb.uri=mongodb://user:pass@localhost:27017/test
  redis:
    host: 129.204.23.55
#  data:
#    mongodb:
#      uri: mongodb://user:pass@129.204.23.55:27017/spitdb