server:
  port: 9008
spring:
  application:
    name: wanttosay_user #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_user
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      database: spitdb
  redis:
    host: 129.204.23.55
  rabbitmq:
    host:129.204.23.55
  jwt:
    config:
      key:coolhy
      time:360000
