server:
  port: 9007

spring:
  application:
    name: wanttosay-search
  data:
    elasticsearch:
      cluster-nodes: 129.204.23.55:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
  prefer-ip-address: true
