server:
  port: 9005
spring:
  application:
    name: wanttosay_gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql