server:
  port: 9004
spring:
  application:
    name: wanttosay-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_article
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 129.204.23.55
    port: 6379
  data:
    mongodb:
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka

