server:
  port: 9005
spring:
  application:
    name: wanttosay-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
  prefer-ip-address: true
