server:
  port: 9001
spring:
  application:
    name:wanttosay-base  #springcloud 取别名必须用横杠，不能用下划线
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_base
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true