server:
  port: 9003
spring:
  application:
    name: wanttosay-qa  #springcloud 取别名必须用横杠，不能用下划线
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanttosay_qa
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
  prefer-ip-address: true
  feign:
    hystrix:
      enabled: true
